import type { FileNode, Message } from "$lib/tauri/types";

export const demoFiles: FileNode[] = [
  {
    name: "src",
    path: "src",
    is_dir: true,
    children: [
      {
        name: "main.py",
        path: "src/main.py",
        is_dir: false,
        language: "python",
        content: '#!/usr/bin/env python3\n"""Entry point for the application."""\n\nfrom app import create_app\nfrom config import settings\n\n\ndef main():\n    app = create_app(settings)\n    app.run(\n        host=settings.HOST,\n        port=settings.PORT,\n        debug=settings.DEBUG\n    )\n\n\nif __name__ == "__main__":\n    main()',
      },
      {
        name: "app.py",
        path: "src/app.py",
        is_dir: false,
        language: "python",
        content: 'from flask import Flask\n\n\ndef create_app(config):\n    app = Flask(__name__)\n    app.config.from_object(config)\n    return app',
      },
      {
        name: "config.py",
        path: "src/config.py",
        is_dir: false,
        language: "python",
        content: 'import os\n\n\nclass Settings:\n    HOST = os.getenv("HOST", "0.0.0.0")\n    PORT = int(os.getenv("PORT", 8080))\n    DEBUG = os.getenv("DEBUG", "false").lower() == "true"\n    DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///app.db")\n\n\nsettings = Settings()',
      },
      {
        name: "models",
        path: "src/models",
        is_dir: true,
        children: [
          { name: "__init__.py", path: "src/models/__init__.py", is_dir: false, language: "python", content: "" },
          {
            name: "user.py",
            path: "src/models/user.py",
            is_dir: false,
            language: "python",
            content: 'from dataclasses import dataclass\n\n\n@dataclass\nclass User:\n    id: int\n    name: str\n    email: str',
          },
        ],
      },
      {
        name: "routes",
        path: "src/routes",
        is_dir: true,
        children: [
          { name: "__init__.py", path: "src/routes/__init__.py", is_dir: false, language: "python", content: "" },
          {
            name: "api.py",
            path: "src/routes/api.py",
            is_dir: false,
            language: "python",
            content: 'from flask import Blueprint, jsonify\n\napi = Blueprint("api", __name__)\n\n\n@api.route("/health")\ndef health():\n    return jsonify({"status": "ok"})',
          },
        ],
      },
    ],
  },
  {
    name: "tests",
    path: "tests",
    is_dir: true,
    children: [
      {
        name: "test_app.py",
        path: "tests/test_app.py",
        is_dir: false,
        language: "python",
        content: 'import pytest\nfrom app import create_app\nfrom config import Settings\n\n\ndef test_create_app():\n    app = create_app(Settings())\n    assert app is not None',
      },
    ],
  },
  {
    name: "requirements.txt",
    path: "requirements.txt",
    is_dir: false,
    language: "text",
    content: "flask==3.0.0\npytest==7.4.3\ngunicorn==21.2.0",
  },
  {
    name: "README.md",
    path: "README.md",
    is_dir: false,
    language: "markdown",
    content: "# My App\n\nA simple Flask application.\n\n## Setup\n\n```bash\npip install -r requirements.txt\npython src/main.py\n```",
  },
  {
    name: ".gitignore",
    path: ".gitignore",
    is_dir: false,
    language: "text",
    content: "__pycache__/\n*.pyc\n.env\nvenv/\n*.db",
  },
];

export const demoMessages: Message[] = [
  {
    role: "user",
    id: "demo-1",
    timestamp: "14:23:01",
    content: "Add authentication middleware to the Flask app with JWT support",
  },
  {
    role: "agent",
    type: "text",
    id: "demo-2",
    timestamp: "14:23:02",
    content: "I'll add JWT authentication to your Flask app. Let me analyze the current structure and implement the changes.",
    thinking: "Analyzing project structure... Found Flask app in src/app.py with basic setup. Need to add: 1) JWT dependency, 2) auth middleware module, 3) decorator for protected routes, 4) update app factory.",
  },
  {
    role: "agent",
    type: "action",
    id: "demo-3",
    timestamp: "14:23:04",
    action: { kind: "read", path: "src/app.py", line_range: [1, 7] },
    status: "applied",
  },
  {
    role: "agent",
    type: "action",
    id: "demo-4",
    timestamp: "14:23:05",
    action: { kind: "read", path: "src/config.py", line_range: [1, 10] },
    status: "applied",
  },
  {
    role: "agent",
    type: "action",
    id: "demo-5",
    timestamp: "14:23:07",
    action: {
      kind: "create",
      path: "src/auth.py",
      language: "python",
      content: 'import jwt\nfrom functools import wraps\nfrom flask import request, jsonify, current_app\nfrom datetime import datetime, timedelta\n\n\ndef create_token(user_id: int) -> str:\n    payload = {\n        "sub": user_id,\n        "iat": datetime.utcnow(),\n        "exp": datetime.utcnow() + timedelta(hours=24)\n    }\n    return jwt.encode(\n        payload,\n        current_app.config["SECRET_KEY"],\n        algorithm="HS256"\n    )\n\n\ndef require_auth(f):\n    @wraps(f)\n    def decorated(*args, **kwargs):\n        token = request.headers.get("Authorization", "").replace("Bearer ", "")\n        if not token:\n            return jsonify({"error": "Missing token"}), 401\n        try:\n            payload = jwt.decode(\n                token,\n                current_app.config["SECRET_KEY"],\n                algorithms=["HS256"]\n            )\n            request.user_id = payload["sub"]\n        except jwt.ExpiredSignatureError:\n            return jsonify({"error": "Token expired"}), 401\n        except jwt.InvalidTokenError:\n            return jsonify({"error": "Invalid token"}), 401\n        return f(*args, **kwargs)\n    return decorated',
    },
    status: "applied",
  },
  {
    role: "agent",
    type: "action",
    id: "demo-6",
    timestamp: "14:23:10",
    action: {
      kind: "edit",
      path: "src/app.py",
      diff: [
        { type: "context", content: "from flask import Flask" },
        { type: "add", content: "from auth import require_auth" },
        { type: "context", content: "" },
        { type: "context", content: "" },
        { type: "context", content: "def create_app(config):" },
        { type: "context", content: '    app = Flask(__name__)' },
        { type: "context", content: '    app.config.from_object(config)' },
        { type: "add", content: '    app.config["SECRET_KEY"] = config.SECRET_KEY' },
        { type: "add", content: '' },
        { type: "add", content: '    from routes.api import api' },
        { type: "add", content: '    app.register_blueprint(api, url_prefix="/api")' },
        { type: "context", content: '    return app' },
      ],
    },
    status: "applied",
  },
  {
    role: "agent",
    type: "action",
    id: "demo-7",
    timestamp: "14:23:12",
    action: {
      kind: "edit",
      path: "src/config.py",
      diff: [
        { type: "context", content: 'import os' },
        { type: "add", content: 'import secrets' },
        { type: "context", content: '' },
        { type: "context", content: '' },
        { type: "context", content: 'class Settings:' },
        { type: "context", content: '    HOST = os.getenv("HOST", "0.0.0.0")' },
        { type: "context", content: '    PORT = int(os.getenv("PORT", 8080))' },
        { type: "context", content: '    DEBUG = os.getenv("DEBUG", "false").lower() == "true"' },
        { type: "context", content: '    DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///app.db")' },
        { type: "add", content: '    SECRET_KEY = os.getenv("SECRET_KEY", secrets.token_hex(32))' },
      ],
    },
    status: "applied",
  },
  {
    role: "agent",
    type: "action",
    id: "demo-8",
    timestamp: "14:23:13",
    action: {
      kind: "edit",
      path: "requirements.txt",
      diff: [
        { type: "context", content: "flask==3.0.0" },
        { type: "add", content: "PyJWT==2.8.0" },
        { type: "context", content: "pytest==7.4.3" },
        { type: "context", content: "gunicorn==21.2.0" },
      ],
    },
    status: "applied",
  },
  {
    role: "agent",
    type: "text",
    id: "demo-9",
    timestamp: "14:23:14",
    content: "Done. I've added JWT authentication to your app:\n\n• Created `src/auth.py` — token creation and `@require_auth` decorator\n• Updated `src/app.py` — imports auth, registers blueprints, sets SECRET_KEY\n• Updated `src/config.py` — added SECRET_KEY with auto-generation\n• Updated `requirements.txt` — added PyJWT dependency\n\nTo protect any route, just add the decorator:\n\n```python\n@api.route(\"/protected\")\n@require_auth\ndef protected():\n    return jsonify({\"user\": request.user_id})\n```",
  },
];
